import { app, BrowserWindow, shell } from 'electron';
import path from 'node:path';
import { registerIpc } from './ipc';
import { resolveRepoRoot } from './registry';

const isDev = !!process.env['ELECTRON_RENDERER_URL'];

// Resolved from desktop/out/main/index.js → up 2 → renderer/public/icon.png.
// Generated by `renderer/scripts/gen-favicon.mjs` (npm run gen:favicon).
const ICON_PATH = path.join(__dirname, '../../renderer/public/icon.png');

// Windows: bind a stable Application User Model ID so Explorer groups the
// window under one taskbar entry (and picks up our icon on pinning). No-op
// on macOS/Linux. Called before any window is created.
if (process.platform === 'win32') {
    app.setAppUserModelId('dev.pphat.kfe.icons-studio');
}

function createWindow(): void {
    const win = new BrowserWindow({
        width: 1440,
        height: 900,
        minWidth: 1080,
        minHeight: 680,
        backgroundColor: '#0a0a0a',
        show: false,
        autoHideMenuBar: true,
        title: 'KFe Icons',
        icon: ICON_PATH,
        webPreferences: {
            preload: path.join(__dirname, '../preload/index.js'),
            sandbox: false,
            contextIsolation: true,
            nodeIntegration: false,
        },
    });

    win.once('ready-to-show', () => win.show());

    // External links open in the OS browser, not a new Electron window.
    win.webContents.setWindowOpenHandler(({ url }) => {
        shell.openExternal(url);
        return { action: 'deny' };
    });

    if (isDev) {
        win.loadURL(process.env['ELECTRON_RENDERER_URL']!);
    } else {
        // Next.js static export lands under renderer/out/
        win.loadFile(path.join(__dirname, '../../renderer/out/index.html'));
    }
}

app.whenReady().then(() => {
    const repoRoot = resolveRepoRoot();
    registerIpc(repoRoot);
    createWindow();

    app.on('activate', () => {
        if (BrowserWindow.getAllWindows().length === 0) createWindow();
    });
});

app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') app.quit();
});
